apiVersion: rp5.reportportal.io/v1alpha1
kind: ReportPortal
metadata:
  name: example-reportportal
spec:
  # You cluster default router hostname
  app_domain: apps.test-example.com
  ui_replicas: 1
  api_replicas: 1
  index_replicas: 1
  gateway_replicas: 1
