apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: reportportals.rp5.reportportal.io
spec:
  group: rp5.reportportal.io
  names:
    kind: ReportPortal
    listKind: ReportPortalList
    plural: reportportals
    singular: reportportal
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
